version: 2

models:
  - name: orders
    description: "Kiểm thử chất lượng dữ liệu bảng orders"
    columns:
      - name: order_id
        description: "order_id là định danh duy nhất cho mỗi đơn hàng"
        tests:
          - unique
          - not_null

      - name: customer_id
        description: "Khách hàng đã đặt đơn hàng"
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: customer_id

      
      - name: total_amount
        description: "Tổng số tiền đơn hàng (phải lớn hơn hoặc bằng 0)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      
      - name: payment_method_id
        description: "Phương thức thanh toán được sử dụng cho đơn hàng (phải có giá trị hợp lệ)"
        tests:
          - not_null
          - relationships:
              to: ref('payment_method')
              field: payment_method_id

  - name: orders_items
    description: "Order line items"
    columns:
      - name: order_item_id
        description: "Định danh duy nhất cho mỗi mục đơn hàng"
        tests:
          - unique
          - not_null
      
      - name: order_id
        description: "Đơn hàng mà mục này thuộc về"
        tests:
          - not_null
          - relationships:
              to: ref('orders')
              field: order_id
      
      - name: product_id
        description: "Sản phẩm được đặt"
        tests:
          - not_null
          - relationships:
              to: ref('products')
              field: product_id
      
      # - name: quantity
      #   description: "Số lượng được đặt"
      #   tests:
      #     - not_null
      #     - dbt_utils.accepted_range:
      #         min_value: 1
      #         max_value: 1000
      

  - name: customers
    description: "Customer master data"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
    

  - name: products
    description: "Product master data"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null
      
      
      - name: category_id
        description: "Product category"
        tests:
          - not_null
          - relationships:
              to: ref('categories')
              field: category_id
      
      - name: brand_id
        description: "Product brand"
        tests:
          - relationships:
              to: ref('brands')
              field: brand_id
      

  - name: categories
    description: "Product categories"
    columns:
      - name: category_id
        description: "Định danh duy nhất cho mỗi danh mục"
        tests:
          - unique
          - not_null

  - name: brands
    description: "Product brands"
    columns:
      - name: brand_id
        description: "Định danh duy nhất cho mỗi thương hiệu"
        tests:
          - unique
          - not_null

  - name: payment_method
    description: "Phương thức thanh toán"
    columns:
      - name: payment_method_id
        description: "Định danh duy nhất cho mỗi phương thức thanh toán"
        tests:
          - unique
          - not_null
    
