image:
  repository: trinodb/trino
  tag: "472"

service:

  type: NodePort


server:
  workers: 2
  config:
    https:
      enabled: true
      port: 8443
      keystore:
        path: "/etc/trino/ssl/trino_cert.jks"
        key: "abc123"
    authenticationType: "PASSWORD"
  coordinatorExtraConfig: |
    password-authenticator.config-files=/etc/trino/password_db.properties

accessControl:
  type: properties
  properties: |
    access-control.name=ranger
    ranger.service.name=dev_trino
    ranger.plugin.config.resource=/etc/trino/ranger-trino-security.xml,/etc/trino/ranger-trino-audit.xml,/etc/trino/ranger-policymgr-ssl.xml

additionalConfigProperties: 
  - internal-communication.shared-secret=trino-minio-ranger-example
  - internal-communication.https.required=true
  - internal-communication.http2.enabled=false
  - http-server.https.enabled=true
  - http-server.https.keystore.path=/etc/trino/ssl/trino_cert.jks
  - http-server.https.keystore.key=abc123

worker:
  additionalVolumes:
    - name: trino-certs
      secret:
        secretName: trino-ssl-secret

  additionalVolumeMounts:
    - name: trino-certs
      mountPath: /etc/trino/ssl
      readOnly: true

coordinator:
  additionalExposedPorts:
    https:
      servicePort: 8443
      name: https
      port: 8443
      protocol: TCP

  additionalVolumes:
    - name: trino-certs
      secret:
        secretName: trino-ssl-secret

  additionalVolumeMounts:
    - name: trino-certs
      mountPath: /etc/trino/ssl
      readOnly: true

  additionalConfigFiles:
    password_db.properties: |
      password-authenticator.name=file
      file.password-file=/etc/trino/password.db

    password.db: |
      admin:$2y$10$HNvott.IRJ1X6crH2i6R3udsLwUZqSOlb1PveErCuxUlZV.F368SO
      huynq:$2y$10$HNvott.IRJ1X6crH2i6R3udsLwUZqSOlb1PveErCuxUlZV.F368SO
      quyetld:$2y$10$HNvott.IRJ1X6crH2i6R3udsLwUZqSOlb1PveErCuxUlZV.F368SO

    # ranger.plugin.trino.policy.rest.url: http://10.96.89.224:6080
    # ranger.plugin.trino.use.rangerGroups: true
    # ranger.plugin.trino.super.users: admin
    ranger-trino-security.xml: |

      <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
      <configuration xmlns:xi="http://www.w3.org/2001/XInclude">
        <property>
          <name>ranger.plugin.trino.policy.rest.url</name>
          <value>http://10.109.26.35:6080</value>
          <description>MANDATORY: a comma separated list of URLs to Apache Ranger instances in a deployment</description>
        </property>

        <property>
          <name>ranger.plugin.trino.access.cluster.name</name>
          <value></value>
          <description>Name to identify the cluster running the Trino instance. This is recorded in audit logs generated by the plugin</description>
        </property>

        <property>
          <name>ranger.plugin.trino.use.rangerGroups</name>
          <value>true</value>
          <description>Boolean flag to specify whether user-to-groups mapping should be obtained from in Apache Ranger. Default: false</description>
        </property>

        <property>
          <name>ranger.plugin.trino.use.only.rangerGroups</name>
          <value>false</value>
          <description>Boolean flag. true: use only user-to-groups mapping from Apache Ranger; false: use user-to-groups mappings from Apache Ranger and Trino. Default: false</description>
        </property>

        <property>
          <name>ranger.plugin.trino.super.users</name>
          <value>admin</value>
          <description>Comma separated list of user names. Superusers will be authorized for all accesses, without requiring explicit policy grants.</description>
        </property>

        <property>
          <name>ranger.plugin.trino.super.groups</name>
          <value></value>
          <description>Comma separated list of group names. Users in supergroups will be authorized for all accesses, without requiring explicit policy grants</description>
        </property>
      </configuration>

    ranger-trino-audit.xml: |
      <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
      <configuration xmlns:xi="http://www.w3.org/2001/XInclude">
        <property>
          <name>xasecure.audit.is.enabled</name>
          <value>true</value>
          <description>Boolean flag to specify if the plugin should generate access audit logs. Default: true</description>
        </property>

        <property>
          <name>xasecure.audit.solr.is.enabled</name>
          <value>false</value>
          <description>Boolean flag to specify if audit logs should be stored in Solr. Default: false</description>
        </property>

        <property>
          <name>xasecure.audit.solr.solr_url</name>
          <value></value>
          <description>URL to Solr deployment where the plugin should send access audits to</description>
        </property>
        <property>
          <name>xasecure.audit.destination.log4j</name>
          <value>true</value>
        </property>
        <property>
          <name>xasecure.audit.destination.log4j.logger</name>
          <value>ranger_audit</value>
        </property>
      </configuration>
    
    log.properties: |
      # Mức log mặc định cho toàn bộ hệ thống
      io.trino=INFO

      # Bật debug cho Plugin Ranger (Quan trọng nhất để xem Policy nào đang được áp dụng)
      io.trino.plugin.ranger=DEBUG

      # Bật debug cho hệ thống kiểm soát quyền truy cập của Trino
      io.trino.spi.security=DEBUG
      io.trino.security=DEBUG

      # (Tùy chọn) Xem chi tiết quá trình khởi tạo Policy từ Ranger Admin
      org.apache.ranger=DEBUG

    ranger-policymgr-ssl.xml: |
      <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
      <configuration xmlns:xi="http://www.w3.org/2001/XInclude">
        <!-- properties used for 2-way SSL between the Trino plugin and Apache Ranger server -->
        <property>
          <name>xasecure.policymgr.clientssl.keystore</name>
          <value></value>
          <description>Path to keystore file. Only required for two-way SSL. This property should not be included for one-way SSL</description>
        </property>

        <property>
          <name>xasecure.policymgr.clientssl.keystore.type</name>
          <value>jks</value>
          <description>Type of keystore. Default: jks</description>
        </property>

        <property>
          <name>xasecure.policymgr.clientssl.keystore.credential.file</name>
          <value></value>
          <description>Path to credential file for the keystore; the credential should be in alias sslKeyStore. Only required for two-way SSL. This property should not be included for one-way SSL</description>
        </property>

        <property>
          <name>xasecure.policymgr.clientssl.truststore</name>
          <value></value>
          <description>Path to truststore file</description>
        </property>

        <property>
          <name>xasecure.policymgr.clientssl.truststore.type</name>
          <value>jks</value>
          <description>Type of truststore. Default: jks</description>
        </property>

        <property>
          <name>xasecure.policymgr.clientssl.truststore.credential.file</name>
          <value></value>
          <description>Path to credential file for the truststore; the credential should be in alias sslTrustStore</description>
        </property>
      </configuration>


catalogs:
  delta: |
    connector.name=delta-lake
    hive.metastore.uri=thrift://hive-metastore.lakehouse.svc.cluster.local:9083
    fs.native-s3.enabled=true
    s3.aws-access-key=minio
    s3.aws-secret-key=minioadmin123
    s3.endpoint=http://minio-1760084160.lakehouse.svc.cluster.local:9000
    s3.path-style-access=true
    s3.socket-connect-timeout=10m
    s3.socket-read-timeout=10m
    s3.region=us-east-1


resourceGroupsConfig: |-
  {
    "rootGroups": [
      {
        "name": "global",
        "softMemoryLimit": "80%",
        "hardConcurrencyLimit": 100,
        "maxQueued": 100,
        "schedulingPolicy": "fair",
        "jmxExport": true
      },
      {
        "name": "admin",
        "softMemoryLimit": "10%",
        "hardConcurrencyLimit": 20,
        "maxQueued": 10
      },
      {
        "name": "MARKETING TRAFFIC ANALYTICS",
        "softMemoryLimit": "20%",
        "hardConcurrencyLimit": 30,
        "maxQueued": 20
      },
      {
        "name": "Product performance",
        "softMemoryLimit": "25%",
        "hardConcurrencyLimit": 40,
        "maxQueued": 30
      }
    ],
    "selectors": [
      {
        "user": "admin",
        "group": "admin"
      },
      {
        "user": "huynq",
        "group": "MARKETING TRAFFIC ANALYTICS"
      },
      {
        "user": "quyetld",
        "group": "MARKETING TRAFFIC ANALYTICS"
      }
    ]
  }
