apiVersion: apps/v1
kind: Deployment
metadata:
  name: hue
  namespace: lakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hue
  template:
    metadata:
      labels:
        app: hue
    spec:
      containers:
        - name: hue
          image: gethue/hue:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          env:
            - name: HUE_CONF_DIR
              value: /usr/share/hue/desktop/conf
          volumeMounts:
            - name: hue-config
              mountPath: /usr/share/hue/desktop/conf/hue.ini
              subPath: hue.ini
      volumes:
        - name: hue-config
          configMap:
            name: hue-config
